apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kibernate.fullname" . }}
  labels:
    {{- include "kibernate.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kibernate.fullname" . }}
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: {{ include "kibernate.fullname" . }}
