apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "kibernate.fullname" .) | quote }}
  labels:
    {{- include "kibernate.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}