name: Docker Build and Publish
on:
  create:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Docker
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Build
        run: make docker-build
      - name: Docker Push
        run: make docker-buildx-push-ghcr IMAGE_TAGS="latest ${GITHUB_REF#refs/tags/v}"