name: Helm Package and Publish
on:
  workflow_run:
    workflows: ["Docker Build and Publish"]
    types:
      - completed
jobs:
  - name: Helm Package and Publish to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Helm Package
        run: make helm-package
      - name: Helm Publish
        run: make helm-push-ghcr

