name: Helm Package and Publish
on:
  workflow_run:
    workflows: ["Docker Build and Publish"]
    types:
      - completed
jobs:
  helm-package:
    name: Helm Package
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Helm Package
        run: make helm-package
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: helm-package
          retention-days: 1
          path: |
            deployments/helm/kibernate-*.tgz
  helm-publish:
    name: Helm Publish
    needs: helm-package
    runs-on: ubuntu-latest
    steps:
      - name: install helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: refs/heads/gh-pages
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: helm-package
      - name: move artifact into place and generate index
        run: mkdir -p ./helm-charts; mv -f kibernate-*.tgz helm-charts/ && helm repo index ./helm-charts
      - name: set git user config
        run: git config --global user.email "workflow@github-actions.local" && git config --global user.name "GitHub Actions Workflow"
      - name: commit and push
        run: 'git add helm-charts/* && git commit -m "chore(gh-pages): publish release" && git push'


