name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install minikube
        run: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && mv minikube-linux-amd64 /usr/local/bin/minikube && chmod +x /usr/local/bin/minikube
      - name: run all tests
        run: make test